import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { base, heading } from "@/constants/fonts";
import "./globals.css";
import { Provider } from "@/providers";
import UIProvider from "@/components/global/uiprovider";
import { cn } from "@/lib";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground font-base`,
          base.variable,
          heading.variable,
        )}
         cz-shortcut-listen="true"
      >
        <UIProvider>
          <Provider>
            {children}
          </Provider>
        </UIProvider>
      </body>
    </html >
  );
};